/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foretree_cutout_OpenCVJni */

#ifndef _Included_com_foretree_xopencv_OpenCVJni
#define _Included_com_foretree_xopencv_OpenCVJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foretree_xopencv_OpenCVJni
 * Method:    cutout
 * Signature: (Ljava/lang/String;)V
 *
 *
 */
JNIEXPORT jlong JNICALL Java_com_foretree_xopencv_OpenCVJni_cutout
  (JNIEnv *, jclass, jlong);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_initWithImage
  (JNIEnv *, jclass, jlong);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_setCalculateImage
  (JNIEnv *, jclass, jlong, jfloat, jfloat);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_setDrawPoint
  (JNIEnv *, jclass, jobjectArray , jint);
JNIEXPORT jlong JNICALL Java_com_foretree_xopencv_OpenCVJni_selectPoint
  (JNIEnv *, jclass, jobjectArray , jint);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_setDeletePoint
  (JNIEnv *, jclass, jobjectArray , jint);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_resetAllMask
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_redoPoint
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_foretree_xopencv_OpenCVJni_undoPoint
  (JNIEnv *, jclass);
JNIEXPORT jlong JNICALL Java_com_foretree_xopencv_OpenCVJni_getCutResult
  (JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
